### ISSUE TITLE
Report errors per test run

### ISSUE THREAD

**Issue by LarsDenBakker** [LarsDenBakker/web-test-runner#24]
As discussed on slack

```
=== Test run 1 (10:10:21) ===

demo/test/b.test.js
  test b > undefined is a function
    AssertionError: expected undefined to be a function
        at Context.<anonymous> (demo/test/b.test.js:5:29)
  test b > test 0
    Error: Uncaught Error: this error is thrown outside test (demo/test/b.test.js:14)
  Browser logs:
    Uncaught error: Error: this error is thrown outside test
        at demo/test/b.test.js:14:13

=== Test run 2 (10:10:30) ===

demo/test/b.test.js
  test b > undefined is a function
    AssertionError: expected undefined to be a function
        at Context.<anonymous> (demo/test/b.test.js:5:29)
  test b > test 0
    Error: Uncaught Error: this error is thrown outside test (demo/test/b.test.js:14)
  Browser logs:
    Uncaught error: Error: this error is thrown outside test
        at demo/test/b.test.js:14:13

=== Test run 3 (10:10:40) ===

All tests passed!

Finished Test run 3 - Watching for file changes...

Progress: [======    ] 1/1 test files | 14 passed, 1 failed
--- Browsers --
  Chromium: [========  ] 1 failed
  Firefox:  [========= ]
```

**Comment by LarsDenBakker** [comment]
Depends on https://github.com/LarsDenBakker/web-test-runner/issues/12

**Comment by LarsDenBakker** [comment]
Done.
