### ISSUE TITLE
Test and make things work on windows

### ISSUE THREAD

**Issue by LarsDenBakker** [LarsDenBakker/web-test-runner#54]

**Comment by jorenbroekema** [comment]
On WSL2 things work very well so far. On WSL (1) it's tough to make it work because:

1) containerized environments may not have a sandbox working out of the box for puppeteer: it goes more in depth here 
2) WSL has issues with network namespaces so even if you set it up, it may still not work
https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox goes more into it.

Also
3) When running with `args: ['--no-sandbox', '--disable-setuid-sandbox']`, tests would get stuck for unknown reasons, I wasn't able to debug why that happened.

Easiest way for WSL seems to just upgrade to WSL2 https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

**Comment by thepassle** [comment]
On windows 10 playwright seems to just run fine.

Puppeteer runs fine, and runs all the tests as expected, but theres an error when closing the browser:

```bash
Finished running tests!

Chrome: |██████████████████████████████| 34/34 test files | 212 passed, 4 failed

Duration: 5s


(node:17420) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at C:\Users\pasca\web-test-runner\node_modules\puppeteer\lib\Connection.js:56:63
    at new Promise (<anonymous>)
    at Connection.send (C:\Users\pasca\web-test-runner\node_modules\puppeteer\lib\Connection.js:55:16)
    at Page.close (C:\Users\pasca\web-test-runner\node_modules\puppeteer\lib\Page.js:784:44)
    at Page.<anonymous> (C:\Users\pasca\web-test-runner\node_modules\puppeteer\lib\helper.js:117:27)
    at Object.stopSession (C:\Users\pasca\web-test-runner\dist\implementations\browser-launchers\puppeteer-launcher.js:30:22)
    at TestRunner.onSessionFinished (C:\Users\pasca\web-test-runner\dist\core\TestRunner.js:55:29)
    at middleware (C:\Users\pasca\web-test-runner\dist\implementations\servers\es-dev-server.js:86:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Page.<anonymous> (C:\Users\pasca\web-test-runner\node_modules\puppeteer\lib\helper.js:116:19)
    at Object.stopSession (C:\Users\pasca\web-test-runner\dist\implementations\browser-launchers\puppeteer-launcher.js:30:22)
    at TestRunner.onSessionFinished (C:\Users\pasca\web-test-runner\dist\core\TestRunner.js:55:29)
    at middleware (C:\Users\pasca\web-test-runner\dist\implementations\servers\es-dev-server.js:86:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\pasca\web-test-runner\node_modules\koa-compress\index.js:43:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-test-runner@0.0.25 test:bare: `node dist/core/cli.js "demo/test/*.test.js" "--config" "demo/puppeteer.config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-test-runner@0.0.25 test:bare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
